### ISSUE TITLE
the bot doesn't respond to any commands and the console is not in highlighting mode, what is happening?

### ISSUE THREAD

**Issue by PeregrineFalconX** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#100]
**Describe the bug**

**To Reproduce**

**What did you expected to happen**

**What actually happened**

**Screenshots**

**Desktop (please complete the following information):**
 - C-REAL version [e.g. v2.0]

**Additional context**

**Comment by cyxl** [comment]
huh?
