### ISSUE TITLE
Why is c-real.py not working happening?

### ISSUE THREAD

**Issue by Pieczarkaa** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#101]
What's the problem you are having while you are using C-REAL?
When I run c-real.py, it turns off immediately

Have you checked the errors in the console?
Yes or no
yes
![image](https://user-images.githubusercontent.com/108304044/177012545-05179a20-1317-4e81-814e-92718551da0b.png)

**Comment by cyxl** [comment]
is that the full error?

**Comment by TKperson** [comment]
closing because OP didnt respond
