### ISSUE TITLE
Why is 'str' object cannot be interpreted as an integer happening?

### ISSUE THREAD

**Issue by RedBlueKR** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#103]
What's the problem you are having while you are using C-REAL?
'str' object cannot be interpreted as an integer error.

When using commands such as '.kaboom', an error occurs even if 'settings' and 'choice' are defined.(used translator)

**Comment by RedBlueKR** [comment]
@cyxl

**Comment by TKperson** [comment]
Can you post the full error traceback

**Comment by RedBlueKR** [comment]
That's all...
![image](https://user-images.githubusercontent.com/109207093/179470857-aee5f7a8-90f9-4e76-88a5-03ea77b8ca94.png)
![image](https://user-images.githubusercontent.com/109207093/179470865-b85948e9-ef9b-4999-aeaf-7ca21b3745d0.png)
@TKperson

**Comment by RedBlueKR** [comment]
Still not resolved?

**Comment by TKperson** [comment]
It could be caused by miss configuration in the bomb_message random section

Inside of your configuration, I'm guessing, you have some quoted characters inside of a positive integer

**Comment by TKperson** [comment]
Sry for the late reply
We are more active in the discord server

**Comment by RedBlueKR** [comment]
ty

**Comment by RedBlueKR** [comment]
fixed!!
