### ISSUE TITLE
.roleTo Does Not Work./Another problem

### ISSUE THREAD

**Issue by EvDied** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#11]
Made a github account just for this, the roleTo command does not work it gives me this. Weird error about lines and how the attribute isn't there, and also at the moment i can't send a screen-shot cause i just left my house, if you would like a screen shot or think you can fix this by yourself without it the new version let me know please. I also ran into a problem that happens with I think only one of my bots... if i leave it running for a long period of time, it just stops working and wont respond even if i restart i, its just "dead" and i have to remake the JSON file every time, i prefer JSON files and everything this current version is doing, i just wanna see more things fixed such as, ".banAll" and all that stuff and maybe some new commands and even the chance for funny commands, thank you for reading this and listening, i would be happy to talk to you about all the problems and bugs I've ran into, you can contact me on discord "ev#8554" all lowercase and of course remove the quotes

**Comment by EvDied** [comment]
<img width="800" alt="screen shot one" src="https://user-images.githubusercontent.com/75755433/101682304-0b255c00-3a29-11eb-9ede-91a118705841.PNG">
<img width="854" alt="screen shot two" src="https://user-images.githubusercontent.com/75755433/101682318-111b3d00-3a29-11eb-9f1f-68c938785fe8.PNG">
 

Here i got two screen shots, I tried 2 times for reassurance that this was a problem, I also made sure the bot had full perms and etc as I have a testing server for these things.

**Comment by TKperson** [comment]
From the images you sent, it looks like the bot couldn't find black man" in the server. This might be cause by the intents that was added to discord a while ago again.

**Comment by EvDied** [comment]
@TKperson  I tried multiple roles such as "Developer" in my server and even "Administrator" i'm very confused

**Comment by EvDied** [comment]
Anyways, I hope you can try to look into this and fix it, plus .banAll in the next version of this nuker, Much support,I heavily vouch this nuker.

**Comment by TKperson** [comment]
Thanks for the support. roleTo should be fixed now.
