### ISSUE TITLE
Unreadable json formatting in the given configuration file. Make sure the formats are correct

### ISSUE THREAD

**Issue by strangediscord** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#12]
Followed the video exactly to set this up, not sure what's going on here

![Screenshot (227)](https://user-images.githubusercontent.com/76801036/103393123-c00dde80-4ae6-11eb-8953-784df6f87a6c.png)

**Comment by TKperson** [comment]
Can you show your default.json file? With your token removed.

**Comment by TKperson** [comment]
That error will only show up if your json file has some errors in it. It's usually caused by a missing comma, quote, or bracket.

**Comment by strangediscord** [comment]
> That error will only show up if your json file has some errors in it. It's usually caused by a missing comma, quote, or bracket.

{
    "token": "",
    "permissions": [
        "TKperson#2348",
        "cyxl#9986",
        "id",
        "349338062485979136"
    ],
    "bomb_messages": {
        "random": 10,
        "fixed": [
            "BBRP IS NEXT",
            "FUCK U CADE",
            "ezzzzz",
            "adsaddadad"
        ]
    },
    "webhook_spam": {
        "usernames": [
            "\u200b",
            "more names",
            "more names2"
        ],
        "pfp_urls": [
            null
        ],
        "contents": [
            "@everyone Hello DEV was here",
            "@everyone I am on top",
            "@everone BBRP sucks !!",          
        ]
    },
    "bot_permission": "2146958847",
    "command_prefix": ".",
    "bot_status": "offline",
    "verbose": 15,
    "after": [
        "aCat afternuking",
        "aChannel CADE afternuking",
        "sn nuked",
        "si https://ih1.redbubble.net/image.788111706.5520/st,small,507x507-pad,600x600,f8f8f8.u2.jpg"
    ]
}

**Comment by strangediscord** [comment]
> That error will only show up if your json file has some errors in it. It's usually caused by a missing comma, quote, or bracket.


{
    "token": "",
    "permissions": [
        "TKperson#2348",
        "cyxl#9986",
        "id",
        "349338062485979136"
    ],
    "bomb_messages": {
        "random": 10,
        "fixed": [
            "BBRP IS NEXT",
            "FUCK U CADE",
            "ezzzzz",
            "adsaddadad"
        ]
    },
    "webhook_spam": {
        "usernames": [
            "\u200b",
            "more names",
            "more names2"
        ],
        "pfp_urls": [
            null
        ],
        "contents": [
            "@everyone Hello DEV was here",
            "@everyone I am on top",
            "@everone BBRP sucks !!",          
        ]
    },
    "bot_permission": "2146958847",
    "command_prefix": ".",
    "bot_status": "offline",
    "verbose": 15,
    "after": [
        "aCat afternuking",
        "aChannel CADE afternuking",
        "sn nuked",
        "si https://ih1.redbubble.net/image.788111706.5520/st,small,507x507-pad,600x600,f8f8f8.u2.jpg"
    ]
}

**Comment by TKperson** [comment]
```json
{
    "token": "",
    "permissions": [
        "TKperson#2348",
        "cyxl#9986",
        "id",
        "349338062485979136"
    ],
    "bomb_messages":
    {
        "random": 10,
        "fixed": [
            "BBRP IS NEXT",
            "FUCK U CADE",
            "ezzzzz",
            "adsaddadad"
        ]
    },
    "webhook_spam":
    {
        "usernames": [
            "\u200b",
            "more names",
            "more names2"
        ],
        "pfp_urls": [
            null
        ],
        "contents": [
            "@everyone Hello DEV was here",
            "@everyone I am on top",
            "@Everone BBRP sucks !!",
        ]
    },
    "bot_permission": "2146958847",
    "command_prefix": ".",
    "bot_status": "offline",
    "verbose": 15,
    "after": [
        "aCat afternuking",
        "aChannel CADE afternuking",
        "sn nuked",
        "si https://ih1.redbubble.net/image.788111706.5520/st,small,507x507-pad,600x600,f8f8f8.u2.jpg"
    ]
}
```
In the ['webhook_spam']['content'] you had an extra comma at the end of `"@Everone BBRP sucks !!",`. To fix this, just remove the comma after that string which will be `"@Everone BBRP sucks !!"`
