### ISSUE TITLE
SelfBot does not react to commands

### ISSUE THREAD

**Issue by Mr-Inkognito** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#13]
If I try to use commands on a self bot (automated dc account), it is only registering the commands and showing me that I tried to use them, but they do not work.

![Screenshot_2764](https://user-images.githubusercontent.com/56873411/103413459-edf03300-4b79-11eb-891a-ea11d12af921.png)

**Comment by TKperson** [comment]
For selfbots (this version), you have to also give the permission to masterpiss#7837. (I'm going to update the bot so you don't have to do this)

**Comment by TKperson** [comment]
i just updated the bot. Now whoever is in the['permission'] list (AKA Permissions-given-to list) is going to be able to use the bot commands, and whoever is not in it (even the profile owner) is not going to be able to use any bot commands.

**Comment by Mr-Inkognito** [comment]
Ohhh so that's why, anyway thank you so much, gonna try that when I get home
