### ISSUE TITLE
Bot not React

### ISSUE THREAD

**Issue by ImHasanx** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#14]
Bot does not respond to my messages even though I am in the premission list I also do not get a log in the console
![image](https://user-images.githubusercontent.com/31892017/103442902-63cbcb80-4c5a-11eb-8f46-2229d6dc1fd6.png)
![image](https://user-images.githubusercontent.com/31892017/103442918-81993080-4c5a-11eb-8af5-d72fac431665.png)

**Comment by TKperson** [comment]
can you show your json file? And are you using it as a selfbot or normal bot?

**Comment by ImHasanx** [comment]
I start the bot per .exe 

Here is my json file:
{
    "token": "***",
    "permissions": [
        "**", "Haze Baze#8175",
        "**",
        "792212578931441695"
    ],
    "bomb_messages": {
        "random": 10,
        "fixed": [
            "fixed 1",
            "fixed 2",
            "fixed 3",
            "ezzzzz",
            "fixed 5",
            "fixed 6",
            "fixed 7"
        ]
    },
    "webhook_spam": {
        "usernames": [
            "\u200b",
            "more names",
            "more names2"
        ],
        "pfp_urls": [
            null,
            "link to image",
            "link to image2",
            "right now, there's only a 1/4 chance for one of the spammer to not have a pfp"
        ],
        "contents": [
            "Hello was here",
            "on top"
        ]
    },
    "bot_permission": "2146958847",
    "command_prefix": "!",
    "bot_status": "online",
    "verbose": 15,
    "after": [
        "Wurdet ihr genuket?"
    ]
}

**Comment by TKperson** [comment]
Yeah, this time it's my fault I think I messed up something when I was fixing selfbot permission issue.
I'll fix it asap

**Comment by TKperson** [comment]
Ok, it's fixed now
