### ISSUE TITLE
Why is this happening and how can I fix it?

### ISSUE THREAD

**Issue by 2The-Joe** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#17]
C-real tells me "Shared ID is requesting privileged that has not been enabled in the developer portal" after I run the JSON file

**Comment by TKperson** [comment]
Run the json file? The only thing you can run on windows is the exe file. Can you send a screenshot of the error?
And have you turned on these 2 buttons?
<img width="1123" alt="Screenshot" src="https://user-images.githubusercontent.com/50115012/103585164-754de700-4e97-11eb-8f5d-572a3ffa896e.png">

**Comment by 2The-Joe** [comment]
Okay it worked it seems like I didn't pay enough attention to the steps but I still have one question, do I have to be a mod\have managing permissions in the server to perform a bomb?

**Comment by TKperson** [comment]
yes you have to get the permissions before using those commands.

**Comment by TKperson** [comment]
One way to check is to use `<your_prefix>check <@ping>`

**Comment by 2The-Joe** [comment]
Okay, thanks for everything, love u.
