### ISSUE TITLE
Why is my bot not working

### ISSUE THREAD

**Issue by gabcool1369** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#19]
What's the problem you are having while you are using C-REAL? Okay so I got the bot working as a Self-bot but I can't use it with a bot token. I checked the errors, tried a lot of different privileged intents but i'm not sure I get what's the problem. I have attached a picture with the console.

Have you checked the errors in the console?
Yes
![image](https://user-images.githubusercontent.com/27309283/103890851-cc7dd280-50b6-11eb-83fa-cc8314b9f70c.png)

**Comment by TKperson** [comment]
See #17
For normal bots you have to turn on privileged intents2 buttons.
