### ISSUE TITLE
The c-real file opens for a nanosecond and closes.

### ISSUE THREAD

**Issue by TOXIXTV** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#20]
When I open the python file, all it does is opens a console for half a second and closes. I don't know what to do. 
![MToS](https://user-images.githubusercontent.com/74474855/106215719-8e4c6e00-619f-11eb-833b-498ed0067b8e.gif)
Heres a gif of what happens. It's a little hard to see, but it just opens and closes. I have python installed. Am I just being stupid? Did I not read something? How do I fix this???

**Comment by TKperson** [comment]
What version is your python? You can watch the tutorial videos on this GitHub page for setting up

**Comment by TKperson** [comment]
If you want to run it with source code then you probably need to `pip install -r requirements.txt` - the packages. And then try to open it again
