### ISSUE TITLE
Why is this error code happening when I try to type in any command?

### ISSUE THREAD

**Issue by chillyfx** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#21]
What's the problem you are having while you are using C-REAL?

I keep getting this error code whenever I dm the bot a command 
![image](https://user-images.githubusercontent.com/78184969/106217233-cdc88980-61a2-11eb-85c9-aaaeacc27062.png) 

Have you checked the errors in the console?
**Yes** or no

**Comment by TKperson** [comment]
Is this a selfbot or are you using a normal bot?

**Comment by chillyfx** [comment]
Im on the exe thats in the folder

**Comment by TKperson** [comment]
I mean, did you get the account from discord developer portal (normal bot) or is the bot token you are using is an user token?

**Comment by chillyfx** [comment]
Ohhhh I see what you mean I think I might of accidentally used my token should I use the one from the bot page on Discord

**Comment by chillyfx** [comment]
Nvm i looked im using the bots token under the token section and my token for permissions

**Comment by TKperson** [comment]
You can use both, and it's showing that error, then it's a bug.
Can you tell all the steps to reperform that bug? And can you send your default.json here (or on discord TKperson#2348) to me with your token removed?
