### ISSUE TITLE
Keep getting Request cancelled due to -> 401: Unauthorized on the delete commands

### ISSUE THREAD

**Issue by Najmul190** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#22]
![image](https://user-images.githubusercontent.com/68229089/106605055-5d31bc00-6558-11eb-85a2-6d6bf75c6e66.png)
 I keep getting this error every time i try using a command that uses the discord api to delete things, such as emojis and the ban all command. (On the bot)

**Comment by cyxl** [comment]
have you connected to the server?
and is that with every command?

**Comment by Najmul190** [comment]
yeah, i was connected to the server as i used the webhook commands which worked fine. This only happens on the commands that seem to have "https://discord.com/api/v8/guilds/{selected_server.id}/bans/{member.id}" within the code

**Comment by cyxl** [comment]
right now i’m on my phone so I cant help but @TKperson  could know this he is 10x better at discord.py then me. Sorry for the inconvenience if he hasn’t helped you in a few hours I will try when I am back home.

**Comment by cyxl** [comment]
For later reference 

https://discord.com/developers/docs/topics/opcodes-and-status-codes

**Comment by TKperson** [comment]
It looks like the header (the thing that contains your token) has been over written by something in the code. Can you tell me all the commands that you have used?

**Comment by Najmul190** [comment]
yeah it seems to work again for me now, i still haven't a clue why it did that but thanks for the help guys its a brilliant bot
