### ISSUE TITLE
Why is this happening?

### ISSUE THREAD

**Issue by Steam-Xion** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#26]
What's the problem you are having while you are using C-REAL?
After I finish the builder step and put the .json file next to the application file and open it it comes up:

Traceback (most recent call last):
File "c-realv2.py", line 128, in <module>
File "c-realV2.py", line 83, in readJson
File "json\__init__.py", line 293, in load
File "c:\planguages\python\lib\encodings\cp1252.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec cant't decode byte 0x9d in position 559: character maps to <undefined>
[11024] Failed to execute script c=realV2

Then it crashed
I have a feeling it may be due to me adding unicode fonts for in the after area but i have yet to test it

Have you checked the errors in the console?
No

**Comment by TKperson** [comment]
From the error, it does looks like it's cost by some Unicode characters. Can you reply below the Unicode you used?

**Comment by Steam-Xion** [comment]
I have fixed the issue by removing everything in the after section since it was only 1 command
