### ISSUE TITLE
Bug help pls

### ISSUE THREAD

**Issue by rockdude129** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#28]
<img width="596" alt="Screen Shot 2021-02-26 at 1 58 23 PM" src="https://user-images.githubusercontent.com/79297356/109359657-b250ad00-783a-11eb-9d1b-f7bf13e64b3d.png">
it says time not defined

**Comment by TKperson** [comment]
I tried the same command, and it did not show that error. 

So maybe try to restart the bot? I'm not sure why that happened to you.

**Comment by rockdude129** [comment]
Ok thank you it worked :)
