### ISSUE TITLE
massive problem

### ISSUE THREAD

**Issue by endlessXD** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#31]
ur pfp is default, it should be an anime girl pfp, pls change

**Comment by cyxl** [comment]
cringe 😬

**Comment by TKperson** [comment]
Hmm, not planning to change it yet. bc anime pfp usually makes me uncomfortable to "click on" it

**Comment by cyxl** [comment]
arrrggg

**Comment by endlessXD** [comment]
ok understandable
