### ISSUE TITLE
Cannot run bot error

### ISSUE THREAD

**Issue by 2Kernel** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#32]
**Describe the bug**
I made the json file using the html builder and overwrited with the original json file.
But when I run the python file, it shows this error:
 
  File "c-realV2.py", line 403
    if not n.isdigit() or (n := int(n) - 1) < 0:
                             ^
helP!!

**Comment by TKperson** [comment]
Can you copy and paste all the error messages? I can't tell what's wrong with these you gave me. And what did you do to get to this bug?
