### ISSUE TITLE
When i open the executable file it shows the text and then closes 

### ISSUE THREAD

**Issue by sharkboy6969** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#35]
When i open up the exectubale file it shows the text and then instantly closing. also i am pretty sure i have setted up the file correctly

**Comment by TKperson** [comment]
If you are use c-realv2.exe

**Comment by TKperson** [comment]
I'm assuming that you are using windows 10

Causes:
You might be running c-realv2.py (which you need python3.8 or higher and install or update your packages)

You might have an antivirus that blocked executating c-realv2.exe

Also the executable file shouldn't crash at all. I programmed it so it will always pause and output error messages before closing the program.
