### ISSUE TITLE
Why is 'HistoryIterator' object is not iterable happening?

### ISSUE THREAD

**Issue by waifsu** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#36]
Whenever I try and use .clear I always get "'HistoryIterator' object is not iterable"
Is there anyway for me to fix it?

**Comment by TKperson** [comment]
I was originally going to remove that command in the next update (because it was too slow).
I never tried to fix that bug.

If you are fine with ~slow~ deletion of messages then I will fix it in the next update

**Comment by TKperson** [comment]
fixed in 2.3.2
