### ISSUE TITLE
The executable is closing if I try to type something in it 

### ISSUE THREAD

**Issue by epiclashy** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#4]
When I open up the executable, all I see is a blank screen, then if I try to type, it shows lots of white text for a split second and then closes. From what I can see my config file is set up correctly.

**Comment by cyxl** [comment]
@epiclashy  add me on discord cyxl#9986

**Comment by TKperson** [comment]
This should be fixed on V2. Reopen one if it's still an issue.
