### ISSUE TITLE
Commands such as nuke or banAll shouldn't ban people who have perms in the .json file

### ISSUE THREAD

**Issue by shaunx777** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#41]
If you're gonna banAll in a server, i think it should give a choice to not ban trusted users from it. i was thinking maybe a truefalse command would be great as it would allow for framing users in raids

**Comment by TKperson** [comment]
Sure great idea. I'll implement a whitelist for banall/nuke.
