### ISSUE TITLE
Error showing when executing .py file.

### ISSUE THREAD

**Issue by Krainz0** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#42]
So, for some reason, the bot is always showing an error no matter what I do. I already tried updating pips (and discord.py was outdated, actually), but the same error is still showing, so that didn't fix it. I'm using Windows 10, Python 3.9.1 64 bits, and C-REAL 2.3.2, the latest one. 

The error showing up is this (computer user name censored):
![Bot error](https://user-images.githubusercontent.com/75599610/113948692-d7deb800-97e3-11eb-93c9-b1b801e7c1bd.jpg)

**Comment by TKperson** [comment]
It looks like you are using python IDLE
tbh python IDLE is a really bad console. I don't recommend using it (it can't print out special characters)
you should try to run the source code with cmd or something like that.
there's always an option for windows user to use the compiled version of this source code 
https://github.com/TKperson/Nuking-Discord-Server-Bot-Nuke-Bot/releases/download/2.3.2/c-realV2.3.2.zip

**Comment by Krainz0** [comment]
> It looks like you are using python IDLE
> tbh python IDLE is a really bad console. I don't recommend using it (it can't print out special characters)
> you should try to run the source code with cmd or something like that.
> there's always an option for windows user to use the compiled version of this source code
> https://github.com/TKperson/Nuking-Discord-Server-Bot-Nuke-Bot/releases/download/2.3.2/c-realV2.3.2.zip

Thanks, that helped. I tried executing it with py.exe, and it worked fine, no error whatsoever. I'll close this, the problem is solved.
