### ISSUE TITLE
Any crashes (console disappeared), unexpected outcome, and unusable commands?

### ISSUE THREAD

**Issue by jkvhjggfhjyhgggh** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#45]
**Describe the bug**
When I open the exe file, it immediately disappears.
**To Reproduce**
1. Go to 'Bot Code
2. Click on The Python file

**What did you expected to happen**
Show me a bot invite link.
**What actually happened**
It disappears.
**Screenshots**

**Desktop (please complete the following information):**
 - OS: PC
 - C-REAL version: 2.3.2

**Additional context**

**Comment by TKperson** [comment]
They problem might be caused by the following:
1. Your python version isn't 3.8 or higher
2. You don't have all the required module installed with your pip (`pip install -r requirements.txt`) 
3. You didn't turn on the discord intents button ('https://youtu.be/DXnEFoHwL1A?t=44')

**Comment by jkvhjggfhjyhgggh** [comment]
> They problem might be caused by the following:
> 
> 1. Your python version isn't 3.8 or higher
> 2. You don't have all the required module installed with your pip (`pip install -r requirements.txt`)
> 3. You didn't turn on the discord intents button ('https://youtu.be/DXnEFoHwL1A?t=44')

i have done 1 and 3 but for 2 this happens
![image](https://user-images.githubusercontent.com/72280887/114244800-25326500-995d-11eb-9cee-9e82d9e01083.png)

**Comment by TKperson** [comment]
try this:
`pip install discord packaging requests colorama`

**Comment by TKperson** [comment]
do you have the default.json ready?

**Comment by jkvhjggfhjyhgggh** [comment]
> try this:
> `pip install discord packaging requests colorama`

still doesnt work but it last a little longer

**Comment by TKperson** [comment]
are there any errors showing up?

You should try to run this with your cmd

and check your python version with `python -V`

**Comment by TKperson** [comment]
since you are using windows i recommend you run the compiled version so you don't have to install any python related packages.
https://github.com/TKperson/Nuking-Discord-Server-Bot-Nuke-Bot/releases/download/2.3.2/c-realV2.3.2.zip

**Comment by jkvhjggfhjyhgggh** [comment]
> since you are using windows i recommend you run the compiled version so you don't have to install any python related packages.
> https://github.com/TKperson/Nuking-Discord-Server-Bot-Nuke-Bot/releases/download/2.3.2/c-realV2.3.2.zip

how do i use it?

**Comment by TKperson** [comment]
You download this exe file. And then drag your old default.json file into the extracted folder of the exe file. And they run it.

**Comment by jkvhjggfhjyhgggh** [comment]
> You download this exe file. And then drag your old default.json file into the extracted folder of the exe file. And then run it.

what is the .exe file?

**Comment by TKperson** [comment]
it's the compiled version of the source code.
And for how to use it: you can watch the videos I linked on this github page.
