### ISSUE TITLE
Why is the commands prompt asking for path happening?

### ISSUE THREAD

**Issue by jkvhjggfhjyhgggh** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#46]
What's the problem you are having while you are using C-REAL?
The commands prompt asking for path.
Have you checked the errors in the console?
Yes or no
no
![image](https://user-images.githubusercontent.com/72280887/114252802-1bb4f700-9975-11eb-857e-2883c1b140ca.png)

**Comment by TKperson** [comment]
Do you have a file named default.json next to the c-realV2.exe file?

If not, you need to make a default.json with builder.html(you can find a tutorial in this GitHub page), and then drag it next to the .exe file

**Comment by jkvhjggfhjyhgggh** [comment]
> Do you have a file named default.json next to the c-realV2.exe file?
> 
> If not, you need to make a default.json with builder.html(you can find a tutorial in this GitHub page), and then drag it next to the .exe file

Yes.

**Comment by TKperson** [comment]
From what I can see right here 
You might have named the default.json something else like default (1).json
It has to be next to the .exe file and named exactly default.json for it to detect it

**Comment by jkvhjggfhjyhgggh** [comment]
> From what I can see right here
> You might have named the default.json something else like default (1).json
> It has to be next to the .exe file and named exactly default.json for it to detect it

![image](https://user-images.githubusercontent.com/72280887/114254707-f7f6ae80-997e-11eb-9329-6018857b0675.png)

**Comment by TKperson** [comment]
are you inside a zip file?
Have you extracted everything?

**Comment by jkvhjggfhjyhgggh** [comment]
> are you inside a zip file?
> Have you extracted everything?

I am in a zip file. I have extracted everything.

**Comment by jkvhjggfhjyhgggh** [comment]
> > are you inside a zip file?
> > Have you extracted everything?
> 
> I am in a zip file. I have extracted everything.

Well I am in a zip file inside of a new folder.

**Comment by TKperson** [comment]
you should be able to run the bot after extracting everything in the zip file

**Comment by jkvhjggfhjyhgggh** [comment]
> you should be able to run the bot after extracting everything in the zip file

Still doesn't work.

**Comment by TKperson** [comment]
What error did it say this time?

**Comment by jkvhjggfhjyhgggh** [comment]
> What error did it say this time?

The same error.

**Comment by TKperson** [comment]
If the .json file is next to your c-realV2.exe then you are opening the wrong .exe file. You should open the .exe file that is extracted from the zip file.

**Comment by jkvhjggfhjyhgggh** [comment]
> If the .json file is next to your c-realV2.exe then you are opening the wrong .exe file. You should open the .exe file that is extracted from the zip file.

I don't understand.

**Comment by jkvhjggfhjyhgggh** [comment]
Should I just start over again?

**Comment by TKperson** [comment]
I'll walk you over through discord
my discord: TKperson#2348
