### ISSUE TITLE
Command 'webhook attack start [number of times]' doesn't work.

### ISSUE THREAD

**Issue by Krainz0** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#47]
So, the thing is: the command 'webhook attack start [number of times]' won't work. And yes, I already have created the webhooks, and I already did define the targets (no problems whatsoever with that). I have tried executing it with Python 3.8.5 64 bits, 3.9.1 64 bits (both with the py launcher), and the compiled version; the result is the same for all. All the other commands I used worked just fine, nothing wrong with them (I didn't actually try using all of them, but at least, all I have personally used worked without any problems), but this one just doesn't work, no matter what I do. I'm using Windows 10, and C-REAL 2.3.2, latest one. In Python, all pips are installed and updated to latest version.  

And, for a final clarificaction: the console doesn't say absolutely nothing in response, when I try to use the command and nothing happens (I have the default.json file configured so all the 4 logs are activated, by the way).

**Comment by TKperson** [comment]
By define the targets did you mean you used the `webhook attackk all` command?

**Comment by Krainz0** [comment]
> By define the targets did you mean you used the `webhook attackk all` command?

Yes, I did. I used that command.

**Comment by TKperson** [comment]
Can you add me on discord? I'll take this issue in discord TKperson#2348

**Comment by Krainz0** [comment]
> Can you add me on discord? I'll take this issue in discord TKperson#2348

Fine, I'll do right now. I'll add you right now.
