### ISSUE TITLE
I cant run the .py file and there seems to be no .exe

### ISSUE THREAD

**Issue by qwerm14** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#50]
I cant run the .py file and there seems to be no .exe

**Comment by TKperson** [comment]
For the .py you have to download python and install all the required packages.
For .exe I moved it to here: https://github.com/TKperson/Nuking-Discord-Server-Bot-Nuke-Bot/releases/tag/2.3.2

**Comment by qwerm14** [comment]
isn't that the current version? -> https://github.com/TKperson/Nuking-Discord-Server-Bot-Nuke-Bot/releases/tag/2.3.2

**Comment by TKperson** [comment]
yes that's the current version

**Comment by qwerm14** [comment]
Alright, but I still don't see the .exe file here https://github.com/TKperson/Nuking-Discord-Server-Bot-Nuke-Bot/releases/tag/2.3.2

**Comment by TKperson** [comment]
The c-realV2.zip file contains the .exe file
Here's the direct donwload: https://github.com/TKperson/Nuking-Discord-Server-Bot-Nuke-Bot/releases/download/2.3.2/c-realV2.3.2.zip

**Comment by qwerm14** [comment]
Thank you! Have a great night/day!
