### ISSUE TITLE
I have a question?

### ISSUE THREAD

**Issue by qwerm14** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#52]
how do I make the bot spam @everyone or the messages I put in "Contents"  in all the channels it creates?

**Comment by TKperson** [comment]
you need to create 50 channel 
assuming `.` is your prefix
`.channelbomb 50 b64`
and then create 50 webhooks
`.webhook create 50`
add these webhook to attack list
`.webhook attack all`
start spamming 50 times you can change it to a bigger number if you want. I have went up to 3k pings.
`.webhook attack start 50`

**Comment by TKperson** [comment]
note that you can only create 50 webhooks every hour in each server

**Comment by qwerm14** [comment]
Ok, Thank you!

**Comment by qwerm14** [comment]
When I do this command ".webhook attack start 50" it says "Cannot choose from an empty sequence".

**Comment by TKperson** [comment]
have you added the webhooks to the spam/attack list?

**Comment by qwerm14** [comment]
yes i followed your steps, channelbomb 50 b64
and then create 50 webhooks
.webhook create 50
add these webhook to attack list
.webhook attack all
start spamming 50 times you can change it to a bigger number if you want. I have went up to 3k pings.
.webhook attack start 50

**Comment by TKperson** [comment]
maybe somehow the webhooks arent created
use `.webhook` to check if webhooks were created

**Comment by qwerm14** [comment]
Ok.

**Comment by qwerm14** [comment]
The webhooks are there, but after i do the last command " .webhook attack start 50 " it says "Cannot choose from an empty sequence"

**Comment by TKperson** [comment]
check `.webhook attack list` to if theres anything in the spam/attack list

**Comment by qwerm14** [comment]
Yes, there is stuff in there.

**Comment by TKperson** [comment]
oh is it because you don't have anything in the pfp_urls or usernames for webhook_spam config?

**Comment by qwerm14** [comment]
No, i have usernames and stuff in content.

**Comment by TKperson** [comment]
do you also have something in pfp_urls?

**Comment by qwerm14** [comment]
Yes.

**Comment by qwerm14** [comment]
after i do the .nuke command its supposed to do this "webhook create 50
webhook attack all
webhook start 50"

**Comment by qwerm14** [comment]
but it doesn't

**Comment by qwerm14** [comment]
I got the .webhook attack start 50 command to work!

**Comment by TKperson** [comment]
> note that you can only create 50 webhooks every hour in each server

So when you run the .nuke command check to see if you have already create 50 webhooks

**Comment by TKperson** [comment]
> I got the .webhook attack start 50 command to work!

Greate :)

**Comment by qwerm14** [comment]
> > note that you can only create 50 webhooks every hour in each server
> 
> So when you run the .nuke command check to see if you have already create 50 webhooks

Ok

**Comment by qwerm14** [comment]
it didn't create any webhooks with the .nuke command

**Comment by TKperson** [comment]
first off all after nuking the channels will be gone so you need chanelbomb 50 b64 command
and second it hasnt been 1 hour rate limit for you to create another set of 50 webhooks

**Comment by qwerm14** [comment]
when i do the .nuke it creates a bunch of channels and categories, how do i stop it from creating categories?

**Comment by TKperson** [comment]
you probably have .kaboom in your after commands.

There's a way to disable running after command

Use `.nuke false` to run without after commands

**Comment by qwerm14** [comment]
i did that and the categories were still created

**Comment by TKperson** [comment]
the categories were probably being created while you were nuking

**Comment by qwerm14** [comment]
must have been, because when i did the command a second time it worked.

**Comment by qwerm14** [comment]
how do i turn the after commands back on?

**Comment by TKperson** [comment]
run the .nuke command without the false behind it

**Comment by qwerm14** [comment]
Ok.

**Comment by qwerm14** [comment]
the channels come in but they are like random letters

**Comment by qwerm14** [comment]
how do i make them the channels i want

**Comment by TKperson** [comment]
instead of using `.kaboom 50 b64` use commands like `.kaboom 50 fixed`

**Comment by qwerm14** [comment]
Thanks!

**Comment by TKperson** [comment]
np

**Comment by TKperson** [comment]
.nuke is made up with the following commands
1. deleteAllChannels 
2. deleteAllEmojis
3. deleteAllRoles
4. banAll
5. deleteAllWebhooks

You can run the commands separately

**Comment by qwerm14** [comment]
oh, is there a way to make a command that doesn't ban everyone but does everything else or no.

**Comment by TKperson** [comment]
theres no way to run without a command in .nuke
you will have to run the commands separately

**Comment by qwerm14** [comment]
oh
