### ISSUE TITLE
Bot doesnt start (Linux)

### ISSUE THREAD

**Issue by ImHasanx** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#54]
```
File "c-realV2.py", line 142
    if not index.isdigit() or not (0 <= (index := int(index)) <= len(json_paths)):
                                               ^
SyntaxError: invalid syntax

```
Get this error

**Comment by TKperson** [comment]
update your python it needs to be 3.8 or higher

**Comment by ImHasanx** [comment]
`empty range for randrange() (0, 0, 0)`

Kaboom error

**Comment by TKperson** [comment]
You didn't config the "bomb_messages" section

**Comment by TKperson** [comment]
You can use .config command or use the builder.html  from the version before this update (2.3.2)

**Comment by ImHasanx** [comment]
Can u make a mass dm Command?

**Comment by TKperson** [comment]
for normal bots then yes. But for selfbots it's a pain in the ass. I have tried to implement mass dm to selfbots but failed badly (1 week wasted) 

Recently I think I have another idea of making selfbot mass dm come to life.
