### ISSUE TITLE
Why is _____ happening?

### ISSUE THREAD

**Issue by ytJulikus** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#55]
![image](https://user-images.githubusercontent.com/83247643/116293184-e55de100-a796-11eb-85b4-953e5ce07f7c.png)

**Comment by ytJulikus** [comment]
b 404 not found ?

**Comment by cyxl** [comment]
You just launched C-REAL? did you try a command?

**Comment by TKperson** [comment]
I deleted the news.txt that the bot will check for during startup

The 404 note found error is probably the bot was unable to find the news.txt that was here in the last update
