### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by ytJulikus** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#56]
![image](https://user-images.githubusercontent.com/83247643/116293499-45548780-a797-11eb-8d2b-d0274e4702aa.png)

i just copy .exe file from older version to new updated beacuse i want this nujke bot in .exe file and not in .py

**Comment by TKperson** [comment]
The new compiled version is here: https://github.com/TKperson/Nuking-Discord-Server-Bot-Nuke-Bot/releases/download/2.4.0/c-realV2.4.0-win.zip

**Comment by stop-bark** [comment]
make sure you move the default.json file to a folder called data if it does not exist, make one
