### ISSUE TITLE
Not Able To masscreate channels,category,roles

### ISSUE THREAD

**Issue by babbaoi** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#58]
Whenever I type .channelbomb 20 an it displays the error 'NoneType' object cannot be interpreted as an integer. However in the console its showing channelbombing has started. Although it hadnt created a single channel. please help . Also when i do .channelbomb 20 fixed it displays empty range for randrange() (0,0,0)

**Comment by TKperson** [comment]
You need to config it with the `.config` command

**Comment by TKperson** [comment]
On how to use the .config command. You should look at the section above the settings guides

**Comment by TKperson** [comment]
#54 had a similar issue

**Comment by babbaoi** [comment]
Ah Ok Thanks I will Try it
