### ISSUE TITLE
Cant configure repl.it start button

### ISSUE THREAD

**Issue by AdityaParmar101** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#60]
After forking this repo to repl.it
Simple clicking on start button doesnt start the code

```
language = "python3"
run = "python c-realV2.py"```
Still the start button doesnt work
Any help would be appreciated.

**Comment by TKperson** [comment]
You don't actually have to fork it, here's an easier way - all you have to do is to copy and paste the code into the new repl project.

here are the steps copied from: https://www.youtube.com/watch?v=4kBLi9t3oww comment section


first, you have to sign in, then on the top left click "New repl" button. For language select Python. For name choose whatever you want, and click "create repl." After creating a new repl project you can see a text editor in middle of the screen. Inside this text editor you will need to copy and paste the source code from this link: https://raw.githubusercontent.com/TKperson/Nuking-Discord-Server-Bot-Nuke-Bot/master/c-realV2.py
Finally, you want to hit the big green "run" button in top of middle of the website
