### ISSUE TITLE
Any crashes (console disappeared), unexpected outcome, and unusable commands?

### ISSUE THREAD

**Issue by pomerons** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#67]
**Describe the bug**

**To Reproduce**
![Screenshot (58)](https://user-images.githubusercontent.com/84363999/118583849-b74f3980-b763-11eb-9f5b-97e2178f39ab.png)

**What did you expected to happen**

**What actually happened**
whenever I try load up the program it crashes haven't used it in a while. on version 2.3.2 i believe
**Screenshots**

**Desktop (please complete the following information):**
 - C-REAL version [e.g. v2.0]

**Additional context**

**Comment by cyxl** [comment]
First IOS do you mean mac? also we have a discord

**Comment by pomerons** [comment]
I’m on a windows computer I’m not sure why it says iOS and can you send the
discord link

**Comment by cyxl** [comment]
its in the readme
