### ISSUE TITLE
Adding webhook content includes "add" command

### ISSUE THREAD

**Issue by kkjaja** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#69]
**To Reproduce**
1. input ".config webhook_spam contents add (text)"
2. enter ".config webhook_spam contents list"
3. list will display "add (text)"

**What did you expected to happen**

expected "(text)" not "add (text)"

**What actually happened**

"add (text)" appeared on webhooks contents list. inputting ".config webhook_spam contents (text)" does nothing at all, also.

**Screenshots**
![Screenshot (155)](https://user-images.githubusercontent.com/84591899/119181961-ee5d6d80-ba37-11eb-82f1-7dd6fea55688.png)

**Comment by TKperson** [comment]
see #65 
We will not be able to fix this bug until next due to "personal reasons." But you could edit the add out from the default.json file

**Comment by TKperson** [comment]
thanks for reporting

**Comment by kkjaja** [comment]
aaaaaaaaaaaaa the json file! thank you so much

**Comment by TKperson** [comment]
np
