### ISSUE TITLE
all mass channel and kaboom doesnt work

### ISSUE THREAD

**Issue by STORMHELLBOY** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#70]
A series of bombs have been dropped onto ______.
empty range for randrange() (0, 0, 0)

**Comment by TKperson** [comment]
you need to use the .config command to config the kaboom

**Comment by TKperson** [comment]
watch this: https://youtu.be/t6rkj3EPJt8

**Comment by STORMHELLBOY** [comment]
Oh got it thanks
