### ISSUE TITLE
Why is _____ happening?

### ISSUE THREAD

**Issue by ImHasanx** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#71]
i get this error even though i have already installed discord in pip

```
Traceback (most recent call last):
  File "/root/Nuking-Discord-Server-Bot-Nuke-Bot/c-realV2.py", line 30, in <module>
    import discord, sys, requests, os, time

```

**Comment by TKperson** [comment]
Can you post the full trace back? Have you installed the requests module? Or have you upgrade your discord module? There are a few things that can cause those three lines of error
