### ISSUE TITLE
Self-bot does not seem to work

### ISSUE THREAD

**Issue by Krutoy-4el** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#72]
**Describe the bug**
Self-bot doesn't receive and execute any commands.

**To Reproduce**
Just try running any command with self-bot.

**What did you expected to happen**
Running commands.

**What actually happened**
Nothing.

**Desktop (please complete the following information):**
Win10 LTSC x64 (I think it's OS-independent though)
 C-REAL version 2.4.0 (latest)

**What I can add.**
Discord... Oh, I've visited the  [SO question](https://stackoverflow.com/questions/67339174/discord-api-soft-ban-for-selfbot-it-can-only-read-its-own-messages) about this and saw your comments, so you surely have known about this issue. By the way, submitting issue is still great idea, isn't it? :)

**Comment by TKperson** [comment]
The problem was another selfbot nerf issue -- discord won't maintain selfbots anymore, so we have to fix it.

Right now, I haven't pushed out a fix yet. 

Just like you saw in the SO question: Yes I'm aware of the selfbot problem.

**Comment by TKperson** [comment]
Indeed, this is a good question

**Comment by Krutoy-4el** [comment]
Why the issue is closed if it's not fixed yet?

**Comment by cyxl** [comment]
It is closed because we dont support the selfbot anymore sorry for not clarifying.
