### ISSUE TITLE
Thank god I have an antivirus

### ISSUE THREAD

**Issue by RuralAnemone** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#74]
why the smegging hell is this a trojan again?

**Comment by RuralAnemone** [comment]
I mean I suppose it could also not be,
but you'd need to prove it first :)

**Comment by TKperson** [comment]
This is impossible to prove without live opening the program. If you ask me if this is a virus I'll always answer you no. I gave you options on the github page to either trust me or don't. You can run the bot from source code if you don't trust me.

**Comment by RuralAnemone** [comment]
I'm such an idiot, I somehow missed that part of the README...
sorry about that

**Comment by RuralAnemone** [comment]
me rn: 🤡🚬
