### ISSUE TITLE
When using c-realV2.py as selfbot, it will only reply to the user and not anyone in permissions.

### ISSUE THREAD

**Issue by shaunx777** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#75]
I'm using a clean version of c-realV2. When i run the code, it will only reply to me and not anyone in the .json file. it also does not log anyone trying to use the commands.

**Comment by TKperson** [comment]
I'm not sure why this is happening can you provide more information on this problem?

**Comment by shaunx777** [comment]
after downloading an unedited version from the github:
> i ran the .py
> used .config save to create a .json
> edited myself and a friend into the permissions sections by ID
> closed and ran the .py again

i am able to use the selfbot. anyone that i give permissions to, the script does not react to. logs wont say that person doesnt have permission, it will just not do anything. for anyone that tries to do a command while not having the perms, it will log them

**Comment by TKperson** [comment]
In April 30, 2021 selfbots have received (more like discord broke selfbot) a big change (the selfbot version wont receive any message sent by users), so the selfbot version need an update, and I haven't updated the selfbot version one yet. For now, I recommend you use the normal bot version.

I'm not sure where what you meant by unedited version.

**Comment by shaunx777** [comment]
oh, i didnt know this was a change. thanks

by unedited i meant the original code, as i didnt know this was a global issue yet
