### ISSUE TITLE
Why is crashing happening?

### ISSUE THREAD

**Issue by jkvhjggfhjyhgggh** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#86]
What's the problem you are having while you are using C-REAL?
When I run the .py, the Console just crashes.
Have you checked the errors in the console?
Yes or no
no because the console just crashes when I try to run it.

**Comment by TKperson** [comment]
you should join the discord server (link is in the readme)
to get more help 
i barely use this issue page anymore
