### ISSUE TITLE
Whole bot just doesn't seem to work

### ISSUE THREAD

**Issue by Nokijoto** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#9]
Console
![image](https://user-images.githubusercontent.com/51673810/101499261-5b3ee880-396d-11eb-93d4-01a4b9dbedfa.png)
Config file
![image](https://user-images.githubusercontent.com/51673810/101499318-6abe3180-396d-11eb-855a-50af00126be4.png)

**Comment by TKperson** [comment]
I don't know if your discord tag has spaces in them or not. But it looks like in your `permissions` you have spaces between your name and discriminator.

**Comment by TKperson** [comment]
The bot error doesn't have error detection, so if you made a mistake the bot won't tell you anything.
We are working on C-REAL version 2 right now, so I'm hoping that will be much easier to use for normal users.

**Comment by Nokijoto** [comment]
My discord tag dont has spaces in them. I use your builder to create  json file. Probably builder create space in tag.
After change default.json file it work now.
