### ISSUE TITLE
I need help while running the bot

### ISSUE THREAD

**Issue by Anshop-Coder** [TKperson/Nuking-Discord-Server-Bot-Nuke-Bot#90]
What's the problem you are having while you are using C-REAL?

Have you checked the errors in the console?
Yes or no

**Comment by TKperson** [comment]
refer to this: https://github.com/TKperson/Nuking-Discord-Server-Bot-Nuke-Bot/wiki/Basic-setup-and-knowledge-for-using-the-bot
if you are looking for how to setup the bot
